### ISSUE TITLE
Add real menu names

### ISSUE THREAD

**Issue by rdelaloy** [gwu-libraries/academiccommons-theme#1]
New menu names: Getting Started, Academic Support, Personalized Assistance, Beyond the Classroom, Ask Us

**Getting Started**
Academic Advising
Libraries
Schedules and Courses
Study Spaces
Technology

**Academic Support**
Study Skills
Syllabus Bank
Textbooks

**Personalized Assistance**
Disability and Accessibility
Language Support
Peer Coaching
Research Consultations
Writing Help

**Beyond the Classroom**
Fellowships
Research Opportunities
Workshops and Lectures

**Comment by maxstarkenburg** [comment]
Thanks. What's under "Ask Us"? Or is it just a top-level item only? And I was under the impression that "Ask Us" language was going away (am I mistaken?).

**Comment by rdelaloy** [comment]
Sorry - I was having some kind of aneurysm when I wrote that. Change  Ask Us to Contact Us as a top-level item.

**Comment by maxstarkenburg** [comment]
Point of clarification, please: Are these names to match up exactly with the what's on the homepage and/or the corresponding individual page? Or could/should it be "Disability and Accessibility" in the menu and "Disability and Accessibility Services" on the home/individual page? (The other one I noticed was "Technology" here vs. "Academic Software & Technology" in the mock-up.)
