### ISSUE TITLE
Design of the pop-up for events

### ISSUE THREAD

**Issue by qbaron** [gwu-libraries/academiccommons-theme#24]
The h2 needs to come up a bit. I'm getting some white space between the grey bar and the text that looks a little odd to me.

Also I think we need that box in the right corner to have an "X" on it. I saw something in the commsweb channel about bootstrap maybe overriding something there but we do need to get that fixed.

<img width="708" alt="screen shot 2018-09-06 at 9 01 08 am" src="https://user-images.githubusercontent.com/37844393/45158927-69609600-b1b3-11e8-96c6-13323895ace4.png">

**Comment by maxstarkenburg** [comment]
Ok, I've adjusted the spacing above the header, and removed Bootstrap's JS from the theme, which resolved the "X" issue. I skimmed Bootstrap's docs just to see if it wouldn't jog my memory of some use we're making of that JS, but I didn't see anything familiar.
