### ISSUE TITLE
surface-level changes for pc->tutoring rename mini/quick-rollout

### ISSUE THREAD

**Issue by maxstarkenburg** [gwu-libraries/academiccommons-theme#41]
Making a ticket to tie to a branch to make surface-level changes related to the renaming of Peer Coaching to Tutoring (I think in the theme this should just involve the templates that transform `peer-coaching-old` to `peer-coaching` on the homepage and search results).

**Comment by rdelaloy** [comment]
See comment on [gwu-libraries/Drupal-Modules] surface-level changes for pc->tutoring rename mini/quick-rollout (#154) Should be "peer tutoring."
